url: ALIST_URL
auth:
    username: USERNAME
    password: PASSWORD
token: ALIST_TOKEN
aliyun:
    enable: true
    refresh_token: ALI_YUNPAN_REFRESH_TOKEN
pikpak:
    enable: false
    use_transcoding_address: true
    username: PIKPAK_EMAIL
    password: PIKPAK_PASSWORD
onedrive_app:
    enable: false
    region: global
    tenants:
        - id: 1
          client_id: CLIENT_ID
          client_secret: CLIENT_SECRET
          tenant_id: TENANT_ID
        - id: 2
          client_id: CLIENT_ID
          client_secret: CLIENT_SECRET
          tenant_id: TENANT_ID
